[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "robertojimenez2", email = "robertjim12345@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
