from db.base import Base  
from models.company import Company
from models.user import User
from models.material import Material
from models.surplus import Surplus
from models.need import Need
from models.specification import Specification
from models.surplus_specification import SurplusSpecification
from models.need_specification import NeedSpecification
from models.offer import Offer
from models.transaction import Transaction