"""add specification uniqueness

Revision ID: 42441b57d02c
Revises: 4d957feeb912
Create Date: 2026-09-21 17:56:21.621437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42441b57d02c'
down_revision: Union[str, Sequence[str], None] = '4d957feeb912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_specification_material_name', 'specifications', ['material_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_specification_material_name', 'specifications', type_='unique')
    # ### end Alembic commands ###
