"""add surplus and need specifications

Revision ID: 4d957feeb912
Revises: 7259a70e3ca6
Create Date: 2026-09-21 17:48:01.236531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d957feeb912'
down_revision: Union[str, Sequence[str], None] = '7259a70e3ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('need_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('need_id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('value_number', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('min_value_number', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('max_value_number', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('value_text', sa.String(length=255), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['need_id'], ['needs.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_need_specifications_need_id'), 'need_specifications', ['need_id'], unique=False)
    op.create_index(op.f('ix_need_specifications_specification_id'), 'need_specifications', ['specification_id'], unique=False)
    op.create_table('surplus_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surplus_id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('value_number', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('value_text', sa.String(length=255), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], ),
    sa.ForeignKeyConstraint(['surplus_id'], ['surpluses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surplus_specifications_specification_id'), 'surplus_specifications', ['specification_id'], unique=False)
    op.create_index(op.f('ix_surplus_specifications_surplus_id'), 'surplus_specifications', ['surplus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surplus_specifications_surplus_id'), table_name='surplus_specifications')
    op.drop_index(op.f('ix_surplus_specifications_specification_id'), table_name='surplus_specifications')
    op.drop_table('surplus_specifications')
    op.drop_index(op.f('ix_need_specifications_specification_id'), table_name='need_specifications')
    op.drop_index(op.f('ix_need_specifications_need_id'), table_name='need_specifications')
    op.drop_table('need_specifications')
    # ### end Alembic commands ###
