"""add offers and transactions

Revision ID: 97a077b478b6
Revises: 0279ba4b0441
Create Date: 2026-09-23 23:46:39.977183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a077b478b6'
down_revision: Union[str, Sequence[str], None] = '0279ba4b0441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surplus_id', sa.Integer(), nullable=False),
    sa.Column('offered_by_company_id', sa.Integer(), nullable=False),
    sa.Column('offered_to_company_id', sa.Integer(), nullable=False),
    sa.Column('parent_offer_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'COUNTERED', 'CANCELLED', 'EXPIRED', name='offerstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offered_by_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['offered_to_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['surplus_id'], ['surpluses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_offered_by_company_id'), 'offers', ['offered_by_company_id'], unique=False)
    op.create_index(op.f('ix_offers_offered_to_company_id'), 'offers', ['offered_to_company_id'], unique=False)
    op.create_index(op.f('ix_offers_parent_offer_id'), 'offers', ['parent_offer_id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_index(op.f('ix_offers_surplus_id'), 'offers', ['surplus_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('surplus_id', sa.Integer(), nullable=False),
    sa.Column('seller_company_id', sa.Integer(), nullable=False),
    sa.Column('buyer_company_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED', name='transactionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['seller_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['surplus_id'], ['surpluses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_buyer_company_id'), 'transactions', ['buyer_company_id'], unique=False)
    op.create_index(op.f('ix_transactions_offer_id'), 'transactions', ['offer_id'], unique=True)
    op.create_index(op.f('ix_transactions_seller_company_id'), 'transactions', ['seller_company_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_surplus_id'), 'transactions', ['surplus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_surplus_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_seller_company_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_offer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_buyer_company_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_offers_surplus_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_parent_offer_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_offered_to_company_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_offered_by_company_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
