"""add needs

Revision ID: a219fe4243a7
Revises: c6ad18640a80
Create Date: 2026-09-21 17:35:20.991570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a219fe4243a7'
down_revision: Union[str, Sequence[str], None] = 'c6ad18640a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('needs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_needs_company_id'), 'needs', ['company_id'], unique=False)
    op.create_index(op.f('ix_needs_material_id'), 'needs', ['material_id'], unique=False)
    op.create_index(op.f('ix_needs_status'), 'needs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_needs_status'), table_name='needs')
    op.drop_index(op.f('ix_needs_material_id'), table_name='needs')
    op.drop_index(op.f('ix_needs_company_id'), table_name='needs')
    op.drop_table('needs')
    # ### end Alembic commands ###
