"""add material status and proposed_by

Revision ID: a54fe6c9ffe1
Revises: bcd22804956a
Create Date: 2026-09-23 22:03:19.796488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54fe6c9ffe1'
down_revision: Union[str, Sequence[str], None] = 'bcd22804956a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'materials',
        sa.Column(
            'status',
            sa.String(length=20),
            nullable=False,
        )
    )
    op.add_column('materials', sa.Column('proposed_by_company_id', sa.Integer(), nullable=True))
    op.add_column(
        'materials',
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        )
    )
    op.alter_column('materials', 'updated_at', server_default=None)
    op.create_index(op.f('ix_materials_proposed_by_company_id'), 'materials', ['proposed_by_company_id'], unique=False)
    op.create_index(op.f('ix_materials_status'), 'materials', ['status'], unique=False)
    op.create_foreign_key(None, 'materials', 'companies', ['proposed_by_company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_index(op.f('ix_materials_status'), table_name='materials')
    op.drop_index(op.f('ix_materials_proposed_by_company_id'), table_name='materials')
    op.drop_column('materials', 'updated_at')
    op.drop_column('materials', 'proposed_by_company_id')
    op.drop_column('materials', 'status')
    # ### end Alembic commands ###
